In [2]:
import numpy as np
arr = np.array([1, 2])
scalar=5

#broadcasting
result=arr+scalar
print(result)

matrix = np.array([[1, 2], [3, 4]])
print(matrix+arr)

[6 7]
[[2 4]
 [4 6]]


#### random number generation

In [10]:
np.random.seed(0)
random_array = np.random.rand(3)
random_array2=np.random.randint(1,10,5) # Generate 5 random integers between 1 and 10
random_normal=np.random.normal(0,1,4) #np.random.normal(mean, std_dev, size)
print("random_array : ",random_array)
print("random_array2 : ",random_array2)
print("random_normal : ",random_normal)


random_array :  [0.5488135  0.71518937 0.60276338]
random_array2 :  [4 8 4 6 3]
random_normal :  [ 0.95008842 -0.15135721 -0.10321885  0.4105985 ]


In [12]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

print(np.dot(A,B))
print(np.matmul(A,B))
print(np.linalg.inv(A))
print(np.linalg.det(A)) #determinant of A

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
