In [1]:
import numpy as np

#### Creating 1D array

In [2]:
x=np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


#### Creating 2D array

In [3]:
y=np.array([[1,2,3],[4,5,6]])
print(y)

[[1 2 3]
 [4 5 6]]


#### Creating 3D array

In [4]:
z=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(z)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## Attributes of Numpy array

| Category               | Code                                                         | Description                 |
| ---------------------- | ------------------------------------------------------------ | --------------------------- |
| **Array Creation**     | `arr = np.array([[1,2,3,4,5],[6,7,8,9,10]], dtype=np.int32)` | Creates a 2D NumPy array    |
| **Basic Info**         | `arr.ndim`                                                   | Number of dimensions        |
|                        | `arr.shape`                                                  | Shape (rows, columns)       |
|                        | `arr.size`                                                   | Total elements              |
|                        | `arr.dtype`                                                  | Data type                   |
|                        | `arr.itemsize`                                               | Size of one element (bytes) |
|                        | `arr.nbytes`                                                 | Total memory used           |
|                        | `arr.strides`                                                | Memory step size            |
| **Transformations**    | `arr.T`                                                      | Transpose                   |
|                        | `arr.flatten()`                                              | Convert to 1D               |
|                        | `arr.reshape(5,2)`                                           | Reshape array               |
| **Indexing & Slicing** | `arr[0:2,1:4]`                                               | Sub-array slicing           |
|                        | `arr[arr > 5]`                                               | Boolean indexing            |
| **Broadcasting**       | `arr + 10`                                                   | Add scalar to all elements  |
| **Combining Arrays**   | `np.concatenate((arr, arr), axis=0)`                         | Join arrays (rows)          |
|                        | `np.stack((arr, arr), axis=0)`                               | Stack along new axis        |
|                        | `np.split(arr, 2, axis=0)`                                   | Split into subarrays        |
| **Statistics**         | `np.unique(arr)`                                             | Unique elements             |
|                        | `np.mean(arr)`                                               | Mean                        |
|                        | `np.median(arr)`                                             | Median                      |
|                        | `np.std(arr)`                                                | Standard deviation          |
|                        | `np.var(arr)`                                                | Variance                    |
|                        | `np.min(arr)` / `np.max(arr)`                                | Min / Max                   |
|                        | `np.sum(arr)`                                                | Sum                         |
|                        | `np.prod(arr)`                                               | Product                     |
|                        | `np.cumsum(arr)`                                             | Cumulative sum              |
|                        | `np.cumprod(arr)`                                            | Cumulative product          |
| **Linear Algebra**     | `np.dot(arr, arr.T)`                                         | Dot product                 |
|                        | `np.matmul(arr, arr.T)`                                      | Matrix multiplication       |
|                        | `np.inner(arr[0], arr[1])`                                   | Inner product               |
|                        | `np.outer(arr[0], arr[1])`                                   | Outer product               |
|                        | `np.cross(arr[0], arr[1])`                                   | Cross product               |
| **Element-wise Ops**   | `arr * arr`                                                  | Multiplication              |
|                        | `arr / arr`                                                  | Division                    |
|                        | `arr ** 2`                                                   | Power                       |
|                        | `arr % 2`                                                    | Modulo                      |
|                        | `arr // 2`                                                   | Floor division              |
| **Math Functions**     | `np.abs(arr)`                                                | Absolute value              |
|                        | `np.sign(arr)`                                               | Sign                        |
|                        | `np.round(arr/3)`                                            | Round                       |
|                        | `np.floor(arr/3)`                                            | Floor                       |
|                        | `np.ceil(arr/3)`                                             | Ceil                        |
|                        | `np.trunc(arr/3)`                                            | Truncate                    |
| **Checks / Logical**   | `np.signbit(arr)`                                            | Check sign bit              |
|                        | `np.isfinite(arr)`                                           | Finite check                |
|                        | `np.isinf(arr)`                                              | Infinite check              |
|                        | `np.isnan(arr)`                                              | NaN check                   |
|                        | `np.isneginf(arr)`                                           | Negative infinity           |
|                        | `np.isposinf(arr)`                                           | Positive infinity           |
|                        | `np.iscomplex(arr)`                                          | Complex check               |
|                        | `np.isreal(arr)`                                             | Real check                  |
|                        | `np.isscalar(arr)`                                           | Scalar check                |


In [9]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]],dtype=np.int32)
print(arr)
print("Dimensions:",arr.ndim) #number of dimensions
print("Shape:",arr.shape) #(2,5) means 2 rows and 5 columns
print("Size:",arr.size) #total number of elements in the array
print("Data Type:",arr.dtype) #data type of the elements in the array
print("Item Size:",arr.itemsize) #size of each element in bytes
print("Total Bytes:",arr.nbytes) #total size of the array in bytes

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Dimensions: 2
Shape: (2, 5)
Size: 10
Data Type: int32
Item Size: 4
Total Bytes: 40


In [ ]:
arr=np.array([1,2,3,4,5])
print("Array Original:",arr)
new_arr=arr.astype(np.float64) #convert array to float64
print("Array Converted to Float64:",new_arr)
print("new_arr Data Type:",new_arr.dtype)

Array Original: [1 2 3 4 5]
Array Converted to Float64: [1. 2. 3. 4. 5.]
new_arr Data Type: float64


| Category                | Function / Syntax               | Description                                       | Example                                  |
| ----------------------- | ------------------------------- | ------------------------------------------------- | ---------------------------------------- |
| **From Python Data**    | `np.array()`                    | Create array from list/tuple                      | `np.array([1,2,3])`                      |
|                         | `np.asarray()`                  | Convert input to array (no copy if already array) | `np.asarray([1,2,3])`                    |
| **Range-Based**         | `np.arange(start, stop, step)`  | Like Python `range()`                             | `np.arange(0,10,2)`                      |
|                         | `np.linspace(start, stop, num)` | Equal spaced values                               | `np.linspace(0,1,5)`                     |
|                         | `np.logspace(start, stop, num)` | Log scale values                                  | `np.logspace(1,3,4)`                     |
| **Zeros / Ones / Fill** | `np.zeros(shape)`               | Array of zeros                                    | `np.zeros((2,3))`                        |
|                         | `np.ones(shape)`                | Array of ones                                     | `np.ones((2,3))`                         |
|                         | `np.full(shape, value)`         | Fill with constant                                | `np.full((2,2), 7)`                      |
|                         | `np.empty(shape)`               | Uninitialized array                               | `np.empty((2,2))`                        |
| **Identity / Diagonal** | `np.eye(n)`                     | Identity matrix                                   | `np.eye(3)`                              |
|                         | `np.identity(n)`                | Identity matrix                                   | `np.identity(3)`                         |
|                         | `np.diag()`                     | Create diagonal matrix                            | `np.diag([1,2,3])`                       |
| **Random Arrays**       | `np.random.rand()`              | Uniform (0–1)                                     | `np.random.rand(2,3)`                    |
|                         | `np.random.randn()`             | Normal distribution                               | `np.random.randn(2,3)`                   |
|                         | `np.random.randint()`           | Random integers                                   | `np.random.randint(1,10,(2,3))`          |
|                         | `np.random.random()`            | Random floats                                     | `np.random.random((2,3))`                |
|                         | `np.random.choice()`            | Random selection                                  | `np.random.choice([1,2,3])`              |
| **Like Existing Array** | `np.zeros_like(a)`              | Same shape, zeros                                 | `np.zeros_like(arr)`                     |
|                         | `np.ones_like(a)`               | Same shape, ones                                  | `np.ones_like(arr)`                      |
|                         | `np.full_like(a, val)`          | Same shape, filled                                | `np.full_like(arr, 5)`                   |
| **From Functions**      | `np.fromfunction(func, shape)`  | Create using function                             | `np.fromfunction(lambda i,j: i+j,(2,2))` |
|                         | `np.fromiter(iter, dtype)`      | From iterable                                     | `np.fromiter(range(5), int)`             |
| **Grid Creation**       | `np.meshgrid()`                 | Coordinate matrices                               | `np.meshgrid(x,y)`                       |
| **Buffer / File**       | `np.frombuffer()`               | From buffer                                       | Advanced use                             |
|                         | `np.fromfile()`                 | From file                                         | `np.fromfile('file.txt')`                |


In [10]:
np.zeros((2,3)) #2 rows and 3 columns of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,4)) #3 rows and 4 columns of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])