### list vs numpy array

In [1]:
import numpy as np
import time

In [2]:
py_list = [1,2,3,4,5,6,7,8,9,10]
np_array = np.array(py_list)
start_time = time.time()
result = [x * 2 for x in py_list]
end_time = time.time()
print("List result:", result)
print(f"Time taken: {end_time - start_time} seconds")


start_time = time.time()
result = np_array * 2
end_time = time.time()
print("NumPy result:", result)
print(f"Time taken: {end_time - start_time} seconds")

List result: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
Time taken: 0.0001316070556640625 seconds
NumPy result: [ 2  4  6  8 10 12 14 16 18 20]
Time taken: 0.00011706352233886719 seconds


#### Array creation

In [3]:
#np.arange()
arr_1D=np.arange(10)
print("1D array:", arr_1D)

1D array: [0 1 2 3 4 5 6 7 8 9]


In [4]:
#np.linespace()
arr_linspace=np.linspace(0,1,5)
arr_linspace2=np.linspace(0,10,6).reshape(2,3)
arr_linspace3=np.linspace(0,10,16).reshape(2,2,4)
print(arr_linspace)
print(arr_linspace2)
print(arr_linspace3)


[0.   0.25 0.5  0.75 1.  ]
[[ 0.  2.  4.]
 [ 6.  8. 10.]]
[[[ 0.          0.66666667  1.33333333  2.        ]
  [ 2.66666667  3.33333333  4.          4.66666667]]

 [[ 5.33333333  6.          6.66666667  7.33333333]
  [ 8.          8.66666667  9.33333333 10.        ]]]


In [14]:
np_arr=np.linspace(5,5,5)
print(np_arr)

[5. 5. 5. 5. 5.]


In [13]:
#arr.reshape()
arr=np.arange(12)
print("Original array:", arr)
reshaped_arr=arr.reshape(3,4)
print("Reshaped array:\n", reshaped_arr)

#arr.flatten()
arr_2D=np.array([[1,2,3],[4,5,6]])
print("Original 2D array:\n", arr_2D)
flattened_arr=arr_2D.flatten()
print("Flattened array:", flattened_arr)

#np.concatenate()
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
concatenated_arr=np.concatenate((arr1, arr2))
print("Concatenated array:", concatenated_arr)



Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Original 2D array:
 [[1 2 3]
 [4 5 6]]
Flattened array: [1 2 3 4 5 6]
Concatenated array: [1 2 3 4 5 6]


##### Mathematical operation

In [23]:
#addition
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
added_arr=arr1+arr2
print("Added array:", added_arr)

#substraction
arr1=np.arange(1,6)
arr2=np.arange(6,11)
sub_arr=arr2-arr1
print(
	"Subtracted array:", sub_arr
)
#multiplication
arr2=np.arange(1,6)
arr1=np.arange(1,6)
mul=arr2*arr1
print(mul)

Added array: [5 7 9]
Subtracted array: [5 5 5 5 5]
[ 1  4  9 16 25]


In [24]:
#np.abs(),np.absolute()
arr=np.array([-1,-2,3,-4,5])
abs_arr=np.abs(arr)
print("Absolute values:", abs_arr)
arr=np.array([-1,-2,3,-4,5])
abs_arr2=np.absolute(arr)
print("Absolute values using np.absolute:", abs_arr2)

Absolute values: [1 2 3 4 5]
Absolute values using np.absolute: [1 2 3 4 5]


In [26]:
#unary operators
arr=np.array([1,2,3])
neg_arr=-arr
print("Negated array:", neg_arr)

#comparison operators
arr1=np.array([1,2,3])
arr2=np.array([3,2,1])
print(arr1>2)
print(arr1==arr2)

Negated array: [-1 -2 -3]
[False False  True]
[False  True False]


In [ ]:
#logical operators
arr1=np.arange(8,25)
arr2=np.arange(10,44)
print(np.logical_and(arr1>10, arr1<20))
print(np.logical_or(arr1>8, arr1<30))
print(np.logical_not(arr1>10))



[False False False  True  True  True  True  True  True  True  True  True
 False False False False False]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True]
[ True  True  True False False False False False False False False False
 False False False False False]


In [32]:
#dot product
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.dot(arr1, arr2))

32


In [ ]:
#cross product
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.cross(arr1, arr2))

[-3  6 -3]


In [34]:
#np.sqrt(),np.exp(),np.log()
arr=np.array([1,4,9,16])
print("Square root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Logarithm:", np.log(arr))

Square root: [1. 2. 3. 4.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Logarithm: [0.         1.38629436 2.19722458 2.77258872]


In [36]:
#statistical functions
data=np.array([1,2,3,4,5])
print("Mean:", np.mean(data))
print("Median:", np.median(data))
#print("Mode ", np.mode(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))
print("min:", np.min(data))
print("max:", np.max(data))

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0
min: 1
max: 5


In [39]:
#array indexing and slicing
arr=np.array([10,20,30,40,50])
print(arr>25)
print(arr[[False, False, True, True, True]])
print(arr[arr>25])

[False False  True  True  True]
[30 40 50]
[30 40 50]
